import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { UserNFTs } from '../pageElements/home/UserNFTs';
import { NordleNFTContextProvider } from '../contexts/NordleNFTContext';

const Home: NextPage = () => {
    return (
        <div className="flex min-h-screen flex-col">
            <Head>
                <title>Nordle</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex-grow px-width-clamp py-20">
                <NordleNFTContextProvider>
                    <UserNFTs />
                </NordleNFTContextProvider>
            </main>
            <footer className="flex flex-row justify-end bg-off-black px-width-clamp pt-10 pb-5">
                <p className="text-xl text-off-white">⚡ Jongwon x Yuma 🦎</p>
            </footer>
        </div>
    );
};

export default Home;
